services:
  web:
    image: php:8.2-apache
    ports:
      - "8081:80"
    volumes:
      - ./html:/var/www/html
    depends_on:
      - database
    # InstalÂ·lar els drivers de MySQL necessaris
    command: >
      bash -c "
        docker-php-ext-install mysqli pdo pdo_mysql &&
        apache2-foreground
      "

  database:
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD: contrasenya
      MYSQL_DATABASE: daw_db
      MYSQL_USER: usuari
      MYSQL_PASSWORD: contrasenya
    ports:
      - "3307:3306"
